name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        # Configurar Surge.sh
        npm install --global surge
        surge token <estudiante1> # Reemplazar <estudiante2> con la API Key de Surge de cada estudiante

        # Desplegar en Surge.sh
        surge --project ./ --domain <estudiante1>.surge.sh # Reemplazar <estudiante1> con un subdominio único para cada estudiante
